language: csharp
solution: FluentRestBuilder.sln
sudo: required
dist: trusty

mono: none
dotnet: 1.0.0-preview2-003131

branches:  
  only:
    - master

script:
  - dotnet restore
  - dotnet build */**/project.json
  - dotnet test test\FluentRestBuilder.Test\project.json
  - dotnet test test\FluentRestBuilder.EntityFrameworkCore.Test\project.json