os: Visual Studio 2015

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: dotnet build */**/project.json
  - ps: dotnet test test/FluentRestBuilder.Test/project.json
  - ps: dotnet test test/FluentRestBuilder.EntityFrameworkCore.Test/project.json


test: off 
version: 0.0.1.{build}